include_recipe '../cookbooks/common'
include_recipe '../cookbooks/rust'
include_recipe '../cookbooks/monitoring'
include_recipe '../cookbooks/nginx'
include_recipe '../cookbooks/mysql'
include_recipe '../cookbooks/powerdns'
