include_recipe '../cookbooks/common'
include_recipe '../cookbooks/rust'
include_recipe '../cookbooks/monitoring'
include_recipe '../cookbooks/nginx'
include_recipe '../cookbooks/mysql'
include_recipe '../cookbooks/db_isupipe'
include_recipe '../cookbooks/powerdns'
include_recipe '../cookbooks/isupipe'
